name: Run automated tests on push

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # set up testing-env
      - name: Checkout
        uses: actions/checkout@v3
      # start database
      - name: Start Docker-Container
        run: docker-compose up -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # build and test the programm
      - name: Test
        run: mvn --batch-mode --update-snapshots verify

      - name: Greet person
        run: echo "hello $NAME"
        env:
          NAME: Sengseis